# Generated by Django 6.0 on 2026-07-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_navbarlink_alter_portfoliosettings_cv_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Available for work', max_length=50)),
                ('greeting', models.CharField(default="Hi, I'm", max_length=50)),
                ('name', models.CharField(default='Abdullah', max_length=50)),
                ('typing_phrases', models.TextField(default='Full Stack Developer, React Specialist, API Architect, Problem Solver', help_text='Comma-separated phrases for the typing animation')),
                ('description', models.TextField(default='I craft fast, beautiful, and scalable web applications with 1+ year of hands-on experience building modern digital products that help businesses grow.')),
                ('primary_btn_text', models.CharField(default='Hire Me', max_length=30)),
                ('secondary_btn_text', models.CharField(default='View Portfolio', max_length=30)),
                ('status_badge', models.CharField(default='Open to work', max_length=30)),
                ('stats_number', models.CharField(default='15+', max_length=10)),
                ('stats_text', models.CharField(default='Projects', max_length=30)),
            ],
        ),
    ]
