# Generated by Django 6.0 on 2026-07-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_herosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile picture to replace the default one', null=True, upload_to='hero_images/'),
        ),
    ]
