# Generated by Django 6.0 on 2026-07-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_herosection_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Github, Linkedin, Twitter, Instagram', max_length=30)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='portfoliosettings',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='portfoliosettings',
            name='linkedin_url',
        ),
    ]
