# Generated by Django 6.0 on 2026-07-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_sociallink_remove_portfoliosettings_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='section',
            field=models.CharField(choices=[('Hero', 'Hero Section'), ('Footer', 'Footer Section'), ('All', 'All Sections')], default='All', help_text='Where should this icon appear?', max_length=20),
        ),
    ]
