# Generated by Django 6.0 on 2026-07-10 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_footersection_footersociallink_herosociallink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(default='Abdullah', max_length=50)),
                ('button_text', models.CharField(default='Hire Me', max_length=50)),
                ('button_link', models.CharField(default='#contact', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='navbarlink',
            name='navbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.navbarconfig'),
        ),
    ]
