# Generated by Django 6.0 on 2026-07-10 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_navbarconfig_navbarlink_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='About Me', max_length=50)),
                ('title', models.CharField(default='Building digital experiences that', max_length=100)),
                ('title_highlight', models.CharField(default='drive results', max_length=100)),
                ('description_1', models.TextField(default="I'm Abdullah, a passionate Full Stack Developer with over a year of hands-on experience crafting modern web applications. I specialize in turning complex problems into clean, scalable code and intuitive user experiences.")),
                ('description_2', models.TextField(default='From sleek landing pages to full-scale web apps with secure authentication and APIs, I help businesses around the world ship products that look great and perform even better.')),
                ('profile_image', models.ImageField(blank=True, help_text='Upload a profile picture for the About section', null=True, upload_to='about_images/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(help_text='e.g., Code2, Rocket, Lightbulb', max_length=30)),
                ('label', models.CharField(help_text='e.g., Clean Code', max_length=30)),
                ('value', models.CharField(help_text='e.g., 100%', max_length=30)),
                ('order', models.IntegerField(default=0)),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='portfolio.aboutsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
