# Generated by Django 6.0 on 2026-07-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_skillcategory_skillsection_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
