# Generated by Django 6.0 on 2026-07-10 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_delete_project_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Recent Work', max_length=50)),
                ('title', models.CharField(default='Featured', max_length=100)),
                ('title_highlight', models.CharField(default='projects', max_length=100)),
                ('description', models.TextField(default="A selection of products I've designed and built for clients across the globe.")),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Upload project screenshot', null=True, upload_to='project_images/')),
                ('image_url', models.URLField(blank=True, help_text="Or provide an image URL if you don't want to upload", max_length=500)),
                ('tech_stack', models.CharField(help_text='Comma-separated technologies (e.g., React, Node.js, MongoDB)', max_length=500)),
                ('live_url', models.URLField(blank=True, help_text='URL to live demo')),
                ('github_url', models.URLField(blank=True, help_text='URL to github repo')),
                ('order', models.IntegerField(default=0)),
                ('project_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.projectsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
