# Generated by Django 6.0 on 2026-07-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_projectsection_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Get In Touch', max_length=50)),
                ('title', models.CharField(default="Let's", max_length=100)),
                ('title_highlight', models.CharField(default='work together', max_length=100)),
                ('description', models.TextField(default="Have a project in mind? Send a message and I'll respond within 24 hours.")),
            ],
        ),
    ]
