# Generated by Django 6.0 on 2026-08-17 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_contactsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='My Services', max_length=50)),
                ('title', models.CharField(default='What I', max_length=100)),
                ('title_highlight', models.CharField(default='Offer', max_length=100)),
                ('description', models.TextField(default='I offer a full range of web development services to help you build and grow your digital presence.')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='e.g., Code, Smartphone, Globe, Palette', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('service_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='portfolio.servicesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
