# Generated by Django 6.0 on 2026-08-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_servicesection_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceSection',
        ),
    ]
