# Generated by Django 6.0 on 2026-08-17 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_delete_service_delete_servicesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Services & Pricing', max_length=50)),
                ('title', models.CharField(default='Premium Web', max_length=100)),
                ('title_highlight', models.CharField(default='Packages', max_length=100)),
                ('description', models.TextField(default='Clear, transparent pricing. From simple landing pages to complex full-stack web applications.')),
            ],
        ),
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(help_text="e.g. Rs 15,000 or Let's Talk", max_length=50)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='Enter each feature on a new line')),
                ('highlighted', models.BooleanField(default=False, help_text='Make this package stand out (Recommended)')),
                ('cta_text', models.CharField(default='Start Project', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('pricing_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='portfolio.pricingsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
